steps:
  - name: gcr.io/cloud-builders/gsutil
    entrypoint : bash
    # Use the 'gcr.io/cloud-builders/gsutil' container image to copy files to GCS
    args: 
      - '-c'
      - |
        gsutil -m cp -r  prac_query.sql gs://us-central1-surajcomp-a927308b-bucket/dags/ || exit 1