steps:

  - name: gcr.io/cloud-builders/gsutil
    entrypoint : bash
    args:
      - '-c'
      - |
        echo "name1 ${env_name}"
        envsubst < ${bad_issue.txt} | sponge ${bad_issue.txt}
        


logsBucket: "gs://reflected-slate-452407-n3-logging"
options:
  dynamic_substitutions: true
  automapSubstitutions: true

