steps:

  - name: gcr.io/cloud-builders/gsutil
    entrypoint : bash
    env:
      - env_name=${_ENV_NAME}    
    args: 
      - '-c'
      - |
        echo "name ${_ENV_NAME}"
        echo "name1 env_name"
        envsubst < ${./env_subs.yaml}

  - name: gcr.io/cloud-builders/gsutil
    entrypoint : bash
    # Use the 'gcr.io/cloud-builders/gsutil' container image to copy files to GCS
    args: 
      - '-c'
      - |
        gsutil -m cp -r  * gs://${_BUCKET_NAME}/dags/ || exit 1
        
substitutions:

  _BUCKET_NAME: ""
  _ENV_NAME: ""

logsBucket: "gs://reflected-slate-452407-n3-logging"
options:
  dynamic_substitutions: true
