steps:

  - name: gcr.io/cloud-builders/gsutil
    entrypoint : bash
    args:
      - '-c'
      - |
        echo "name1 ${env_name}"
        $sed 's/${env_name}/env_name/' bad_issue.txt
        gsutil -m cp -r  * gs://${_BUCKET_NAME}/dags/ || exit 1
    env: 
    - env_name=${_ENV_NAME}

substitutions:

  _BUCKET_NAME: ""
  _ENV_NAME: ""

logsBucket: "gs://reflected-slate-452407-n3-logging"
options:
  dynamic_substitutions: true

